# This is an example YAML script for triggering a shell script in an Azure DevOps pipeline

trigger:
  # Define your trigger condition here
  # For example, you can trigger the pipeline when code is pushed to a specific branch
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  # Checkout the code from your repository
  - checkout: self

  # Run your shell script
  - script: |
      chmod +x /Users/amitsavyasachi/Desktop/cicd.sh
      ./cicd.sh

