name: Run Script

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run Script
      run: |
        chmod +x ./path/to/script.sh
        ./path/to/script.sh
