name: Run Script

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run Script
      run: |
       
        echo "Calling Shell Script of testsigma"
        pwd
        ls -la
        chmod a+x script.sh
        .script.sh
